title: SafetyGirl6
author: housleyjj
email: housleyjj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my practice for github pages.  I'm practicing for when I set up my resume and other possible sites.

# social links
twitter_username: I actually do not have a Twitter account
github_username:  housleyjj

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
